#!/bin/bash
alias reload_tmux_conf="tmux source-file ~/.tmux.conf"
alias so="source ~/.bashrc"
alias spip="sudo pip"
alias tmux="tmux -2"
alias vconsole='vssh -t "cd /vagrant/easy_post/ && bundle exec foreman run rails c"'
alias vspec='vssh -t "cd /vagrant/easy_post/ && bundle exec foreman run rspec --color"'
alias vdb='vssh -t "cd /vagrant/easy_post/ && bundle exec foreman run rake db:drop db:create db:migrate db:logs:migrate db:schema:dump db:test:prepare"'

case `uname` in
  'Linux')
    alias ls="ls --color -altr"
    alias pbcopy="xclip -selection clipboard"
    alias pbpaste="xclip -selection clipboard -o"
    ;;
  'Darwin')
    alias ls="ls -Galtr"
    ;;
esac
