#!/bin/bash
alias reload_tmux_conf="tmux source-file ~/.tmux.conf"
alias so="source ~/.bashrc"
alias spip="sudo pip"
alias tmux="tmux -2"

case `uname` in
  'Linux')
    alias ls="ls --color -altr"
    alias pbcopy="xclip -selection clipboard"
    alias pbpaste="xclip -selection clipboard -o"
    ;;
  'Darwin')
    alias ls="ls -Galtr"
    ;;
esac
