#!/bin/bash
alias ls="ls --color -altr"
alias tmux="tmux -2"
alias spip="sudo pip"
alias pbcopy="xclip -selection clipboard"
alias pbpaste="xclip -selection clipboard -o"
alias reload_tmux_conf="tmux source-file ~/.tmux.conf"
