#!/bin/bash

# Opens a SSH connection to the Vagrant VM using a control connection.
function vssh() {
  local control_path="/home/tribone/.vagrant_ssh_control"

  if [[ ! -S $control_path ]]
  then
    vagrant ssh-config | ssh -F /dev/stdin -o "ControlMaster yes" -o "ControlPersist yes" -o "ControlPath $control_path" default $@
  fi

  ssh -o "ControlMaster no" -o "ControlPersist yes" -o "ControlPath $control_path" default $@
}
