#!/bin/bash
alias vconsole='vssh -t "cd /vagrant/easy_post/ && bundle exec foreman run rails c"'
alias vdb='vssh -t "cd /vagrant/easy_post/ && bundle exec foreman run rake db:drop db:create db:migrate db:logs:migrate db:schema:dump db:test:prepare"'
alias vspec='vssh -t "cd /vagrant/easy_post/ && bundle exec foreman run rspec --color"'
alias vbundle='vssh -t "cd /vagrant/easy_post/ && bundle install"'
alias vrake='vssh -t "cd /vagrant/easy_post/ && bundle exec foreman run rake"'

# Open a SSH connection to Vagrant.
function vssh() {
  local control_path="$HOME/.vagrant_ssh_control"

  if [[ ! -S $control_path ]]
  then
    vagrant ssh-config | ssh -F /dev/stdin -o "ControlMaster yes" -o "ControlPersist yes" -o "ControlPath $control_path" default $@
  fi

  ssh -o "ControlMaster no" -o "ControlPersist yes" -o "ControlPath $control_path" default $@
}
