#!/bin/bash
alias vbundle='vssh -t "cd /vagrant/easy_post && bundle update"'
alias vconsole='vrun rails console'
alias vdb='vrun rake db:drop db:create db:migrate db:logs:migrate db:schema:dump db:test:prepare'
alias vrake='vrun rake'
alias vrun='vssh -t "cd /vagrant/easy_post && bundle exec foreman run"'
alias vspec='vrun rspec'

# Open a SSH connection to Vagrant.
function vssh() {
  local control_path="$HOME/.vagrant_ssh_control"

  if [[ ! -S $control_path ]]
  then
    vagrant ssh-config | ssh -F /dev/stdin -o "ControlMaster yes" -o "ControlPersist yes" -o "ControlPath $control_path" default $@
  fi

  ssh -o "ControlMaster no" -o "ControlPersist yes" -o "ControlPath $control_path" default $@
}
